language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t akarpenko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akarpenko/docker-react npm run test